Fix typos
instantdb/instant pull request #32
Opened 2024-08-24 16:25 UTC by szepeviktor

Found few misspellings.

https://github.com/crate-ci/typos

2024-08-24 16:25 UTC, szepeviktor commented
Here is `.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    ".github/actions/elastic-beanstalk/bin/index.js",
    "client/packages/core/__tests__/src/data/zeneca/triples.json",
    "server/dev-resources/triples.csv",
    "server/resources/sample_triples/",
    # Strange plurals
    "client/packages/core/__tests__/src/instaql.test.js",
    "server/src/instant/db/datalog.clj",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Kevin Lacker",
    "\\bC’mone\\b",
    "\\bOT rabbit\\b",
    "(pk_test|pk_live)_[0-9A-Za-z]{72,}",
    "playbackId: '[0-9A-Za-z]+'",
    'playbackId="[0-9A-Za-z]+"',
]

[default.extend-words]
edn = "edn"

[type.clojure.extend-words]
juxt = "juxt"

[default.extend-identifiers]
openpgp4fpr = "openpgp4fpr"

# Typos
"Github" = "GitHub"
```

2024-08-24 16:30 UTC, szepeviktor commented on client/sandbox/react-nextjs/pages/play/ephemeral.tsx
> +    <div className="flex file items-center">
This need attention ⚠️

2024-08-24 23:12 UTC, stopachka approved these changes
This is great, thank you!

2024-08-24 23:16 UTC, stopachka requested changes
(It looks like the clojure tests are failing. It may be transient. I will try to repro this locally when near a computer)

2024-08-29 22:07 UTC, stopachka approved these changes

2024-08-29 22:16 UTC, merged

2024-08-29 22:27 UTC, szepeviktor commented
Glad to contribute.